import { Inter } from "next/font/google";
import "./globals.css";
import { PatientProvider } from '@/contexts/PatientContext';
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PatientProvider>
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </PatientProvider>
    </html>
  );
}
